### ISSUE TITLE
How to make it work with firewalld

### ISSUE THREAD

**Issue by flyhard** [itskenny0/fail2ban-endlessh#1]
I have a system I'd like to use this on that uses firewalld instead of iptables. Is there a way to make this work there as well?

**Comment by JukoiDev** [comment]
bump, i need solution too

**Comment by JukoiDev** [comment]
we can try to change something in action.d/endlessh.conf

also happy new year

**Comment by itskenny0** [comment]
You should probably only need to change the action config to invoke firewalld instead, have a look here:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-port_forwarding

Feel free to submit a patch, I can't currently implement this lacking any firewalld systems.

**Comment by itskenny0** [comment]
Thanks to work by @eetommyj, there is now an action file that can be used with firewalld.
